apiVersion: v1
kind: Service
metadata:
  name: haproxy
  namespace: kube-system
spec:
  ports:
    - port: 8184
      targetPort: haproxy
  externalIPs :
    {{- range .Values.kubevirt.apiserver.externalips }}
    - {{ . }}
    {{- end }}
  selector:
    kubevirt.io: "haproxy"
