apiVersion: v1
kind: Service
metadata:
  name: virt-api
  namespace: kube-system
  labels:
    kubevirt.io: "virt-api"
spec:
  ports:
    - port: 8183
      targetPort: virt-api
  selector:
    kubevirt.io: "virt-api"
